"""Export black-and-white patent-style drawings: orthographic projections.

``projection(cut=false)`` gives the outlines of the model as 2D geometry, which
OpenSCAD can export as SVG and DXF.  DXF opens directly in AutoCAD (add
reference numerals and dimensions there); PNG is produced here by drawing the
SVG polyline data with Pillow, so no extra SVG rasteriser is required.

Usage:
    python lineart.py --model model/device.scad --out-dir figures/黑白附图 \
        [--views front,top,side] [--formats svg,dxf,png] [--json]
"""

from __future__ import annotations

import argparse
import json
import re
import tempfile
from pathlib import Path

from PIL import Image, ImageDraw

from config import find_openscad, load_settings, project_paths
from openscad_run import run_cli

# view name -> rotation applied before projection() (projects along +Z)
VIEW_ROTATIONS: dict[str, list[int]] = {
    "front": [90, 0, 0],
    "back": [90, 0, 180],
    "side": [90, 0, 90],
    "right": [90, 0, 90],
    "left": [90, 0, -90],
    "top": [0, 0, 0],
    "bottom": [180, 0, 0],
}
PATH_RE = re.compile(r'<path[^>]*d="(?P<d>[^"]+)"', re.DOTALL)
NUMBER_RE = re.compile(r"(-?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?)")


def wrap_model(model: Path, rotation: list[int], temp_dir: Path,
               defines: dict[str, str]) -> Path:
    """Write a self-contained wrapper that projects *model* after *rotation*.

    The model source is inlined instead of included: OpenSCAD on this platform
    fails to open ``include`` targets whose path contains non-ASCII characters
    (while the same file works fine as the main file).
    """
    source = model.read_text(encoding="utf-8")
    source = re.sub(r"\n\s*device\(\);\s*$", "\n", source)
    wrapper = temp_dir / "projected.scad"
    define_lines = "\n".join(
        f"{key} = {value};" for key, value in defines.items() if not key.startswith("SET_")
    )
    wrapper.write_text(
        f"// generated by lineart.py（模型已内联）\n{define_lines}\n{source}\n"
        f"projection(cut = false) rotate([{rotation[0]}, {rotation[1]}, {rotation[2]}]) "
        f"device();\n",
        encoding="utf-8",
    )
    return wrapper


def svg_polylines(svg_path: Path) -> list[list[tuple[float, float]]]:
    text = svg_path.read_text(encoding="utf-8", errors="replace")
    polylines: list[list[tuple[float, float]]] = []
    for match in PATH_RE.finditer(text):
        current: list[tuple[float, float]] = []
        for chunk in re.split(r"(?=[MLZ])", match.group("d")):
            chunk = chunk.strip()
            if not chunk:
                continue
            if chunk[0] in "MZ":
                if len(current) > 1:
                    polylines.append(current)
                current = []
                numbers = [float(v) for v in NUMBER_RE.findall(chunk[1:])]
                if len(numbers) >= 2:
                    current = [(numbers[0], numbers[1])]
            elif chunk[0] == "L":
                numbers = [float(v) for v in NUMBER_RE.findall(chunk[1:])]
                for i in range(0, len(numbers) - 1, 2):
                    current.append((numbers[i], numbers[i + 1]))
        if len(current) > 1:
            polylines.append(current)
    return polylines


def polylines_to_png(polylines: list[list[tuple[float, float]]], target: Path,
                     width: int = 1600, margin: int = 60, line_width: int = 3) -> bool:
    points = [p for line in polylines for p in line]
    if not points:
        return False
    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    span_x, span_y = max(xs) - min(xs), max(ys) - min(ys)
    scale = (width - 2 * margin) / max(span_x, 1e-9)
    height = int(span_y * scale) + 2 * margin
    image = Image.new("RGB", (width, max(height, 200)), "white")
    draw = ImageDraw.Draw(image)
    for line in polylines:
        pixels = [((x - min(xs)) * scale + margin, (max(ys) - y) * scale + margin) for x, y in line]
        draw.line(pixels, fill="black", width=line_width, joint="curve")
    target.parent.mkdir(parents=True, exist_ok=True)
    image.save(target)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description="黑白线稿（正投影）导出")
    parser.add_argument("--model", required=True)
    parser.add_argument("--out-dir", required=True)
    parser.add_argument("--project", default=None)
    parser.add_argument("--views", default="front,top,side")
    parser.add_argument("--formats", default="svg,dxf,png")
    parser.add_argument("--define", action="append", default=[])
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    root = Path(args.project).resolve() if args.project else Path.cwd()
    settings = load_settings(root)
    openscad = find_openscad()
    if not openscad:
        raise SystemExit("未找到 OpenSCAD，请设置 OPENSCAD_EXECUTABLE")

    model = Path(args.model)
    if not model.is_absolute():
        model = (root / args.model) if (root / args.model).exists() else project_paths(root)["model"] / args.model
    if not model.exists():
        raise SystemExit(f"模型不存在：{model}")
    out_dir = Path(args.out_dir) if Path(args.out_dir).is_absolute() else root / args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    formats = [f.strip() for f in args.formats.split(",") if f.strip()]
    defines = dict(item.split("=", 1) for item in args.define)

    results = []
    with tempfile.TemporaryDirectory(prefix="p3d_lineart_") as tmp:
        temp_dir = Path(tmp)
        for view in [v.strip() for v in args.views.split(",") if v.strip()]:
            rotation = VIEW_ROTATIONS.get(view)
            if rotation is None:
                results.append({"view": view, "ok": False, "error": "未知视角"})
                continue
            wrapper = wrap_model(model, rotation, temp_dir, defines)
            entry = {"view": view, "files": {}}
            for fmt in formats:
                target = out_dir / f"{model.stem}_{view}.{fmt}"
                argv = ["--backend", "Manifold",
                        "-D", f"SET_FN={settings['scad_fn']}",
                        "-D", f"SET_COIL_SEG={settings['scad_coil_seg']}",
                        "-o", str(target), str(wrapper)]
                result = run_cli(openscad, argv, 600)
                if result.returncode != 0 or not target.exists():
                    entry.update(ok=False,
                                 error=(result.stdout + result.stderr).strip()[-800:])
                    break
                entry["files"][fmt] = str(target)
            if entry.get("files", {}).get("svg") and "png" in formats:
                png = Path(entry["files"]["svg"]).with_suffix(".png")
                if polylines_to_png(svg_polylines(Path(entry["files"]["svg"])), png):
                    entry["files"]["png"] = str(png)
            entry.setdefault("ok", bool(entry["files"]))
            results.append(entry)

    payload = {"model": str(model), "out_dir": str(out_dir),
               "views": results, "ok": all(r.get("ok") for r in results)}
    if args.json:
        print(json.dumps(payload, ensure_ascii=False, indent=2))
    else:
        for entry in results:
            print(f"{entry['view']:6s} {'OK' if entry.get('ok') else 'FAIL'} "
                  + ", ".join(Path(p).name for p in entry.get("files", {}).values()))
    return 0 if payload["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
