"""Export black-and-white patent-style drawings: orthographic projections.

``projection(cut=false)`` gives the outlines of the model as 2D geometry, which
OpenSCAD can export as SVG and DXF.  DXF opens directly in AutoCAD (add
reference numerals and dimensions there); PNG is produced here by drawing the
SVG polyline data with Pillow, so no extra SVG rasteriser is required.

Usage:
    python lineart.py --model model/device.scad --out-dir figures/黑白附图 \
        [--views front,top,side] [--formats svg,dxf,png] [--json]
"""

from __future__ import annotations

import argparse
import json
import re
import tempfile
from pathlib import Path

from PIL import Image, ImageDraw

from config import find_openscad, load_settings, project_paths, read_json
from openscad_run import run_cli

# view name -> rotation applied before projection() (projects along +Z)
VIEW_ROTATIONS: dict[str, list[int]] = {
    "front": [90, 0, 0],
    "back": [90, 0, 180],
    "side": [90, 0, 90],
    "right": [90, 0, 90],
    "left": [90, 0, -90],
    "top": [0, 0, 0],
    "bottom": [180, 0, 0],
}


def model_extent_for(model: Path) -> tuple[float, float] | None:
    """Z range of the model (used to place section cuts)."""
    try:
        from openscad_run import model_extent

        extent = model_extent(model, {}, load_settings(model.parent.parent))
        if not extent:
            return None
        box = extent.get("center", [0, 0, 0])
        size = extent["size"]
        half = size["z"] / 2
        return (box[2] - half, box[2] + half)
    except Exception:
        return None
PATH_RE = re.compile(r'<path[^>]*d="(?P<d>[^"]+)"', re.DOTALL)
NUMBER_RE = re.compile(r"(-?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?)")
FONT_BOLD = [r"C:\Windows\Fonts\msyhbd.ttc", r"C:\Windows\Fonts\msyh.ttc",
             "/System/Library/Fonts/PingFang.ttc",
             "/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc",
             "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"]


def wrap_model(model: Path, rotation: list[int], temp_dir: Path,
               defines: dict[str, str], *, cut: bool = False,
               cut_z: float | None = None, explode: float | None = None,
               tag: str = "view") -> Path:
    """Write a self-contained wrapper that projects *model* after *rotation*.

    The model source is inlined instead of included: OpenSCAD on this platform
    fails to open ``include`` targets whose path contains non-ASCII characters
    (while the same file works fine as the main file).
    """
    from openscad_run import inline_model

    source = inline_model(model)
    wrapper = temp_dir / f"projected_{tag}.scad"
    define_lines = "\n".join(
        f"{key} = {value};" for key, value in defines.items() if not key.startswith("SET_")
    )
    call = "device()"
    if explode is not None:
        call = f"device(explode = {explode})"
    if cut:
        body = (f"projection(cut = true) rotate([{rotation[0]}, {rotation[1]}, {rotation[2]}]) "
                f"translate([0, 0, {-float(cut_z or 0)}]) {call};\n"
                f"projection(cut = false) rotate([{rotation[0]}, {rotation[1]}, {rotation[2]}]) "
                f"translate([0, 0, {-float(cut_z or 0)}]) {call};\n")
    else:
        body = (f"projection(cut = false) rotate([{rotation[0]}, {rotation[1]}, "
                f"{rotation[2]}]) {call};\n")
    wrapper.write_text(
        f"// generated by lineart.py（模型已内联）\n{define_lines}\n{source}\n"
        f"{body}",
        encoding="utf-8",
    )
    return wrapper


def svg_polylines(svg_path: Path) -> list[list[tuple[float, float]]]:
    text = svg_path.read_text(encoding="utf-8", errors="replace")
    polylines: list[list[tuple[float, float]]] = []
    for match in PATH_RE.finditer(text):
        current: list[tuple[float, float]] = []
        for chunk in re.split(r"(?=[MLZ])", match.group("d")):
            chunk = chunk.strip()
            if not chunk:
                continue
            if chunk[0] in "MZ":
                if len(current) > 1:
                    polylines.append(current)
                current = []
                numbers = [float(v) for v in NUMBER_RE.findall(chunk[1:])]
                if len(numbers) >= 2:
                    current = [(numbers[0], numbers[1])]
            elif chunk[0] == "L":
                numbers = [float(v) for v in NUMBER_RE.findall(chunk[1:])]
                for i in range(0, len(numbers) - 1, 2):
                    current.append((numbers[i], numbers[i + 1]))
        if len(current) > 1:
            polylines.append(current)
    return polylines


def polylines_to_png(polylines: list[list[tuple[float, float]]], target: Path,
                     width: int = 1600, margin: int = 110, line_width: int = 3,
                     title: str = "", annotate_size: bool = True) -> bool:
    points = [p for line in polylines for p in line]
    if not points:
        return False
    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    span_x, span_y = max(xs) - min(xs), max(ys) - min(ys)
    scale = (width - 2 * margin) / max(span_x, 1e-9)
    height = int(span_y * scale) + 2 * margin
    image = Image.new("RGB", (width, max(height, 200) + 60), "white")
    draw = ImageDraw.Draw(image)
    for line in polylines:
        pixels = [((x - min(xs)) * scale + margin, (max(ys) - y) * scale + margin) for x, y in line]
        draw.line(pixels, fill="black", width=line_width, joint="curve")
    if title:
        from PIL import ImageFont

        font = None
        for path in FONT_BOLD:
            if Path(path).exists():
                font = ImageFont.truetype(path, 34)
                break
        draw.text((width / 2, 18), title, fill="black", anchor="ma",
                  font=font or ImageFont.load_default())
    if annotate_size and span_x:
        # 尺寸线：横向总宽 / 纵向总高（单位与被投影模型一致，通常为 mm）
        from PIL import ImageFont

        font = None
        for path in FONT_BOLD:
            if Path(path).exists():
                font = ImageFont.truetype(path, 26)
                break
        font = font or ImageFont.load_default()
        y = max(height, 200) - margin + 26
        draw.line([(margin, y), (width - margin, y)], fill="black", width=2)
        for x in (margin, width - margin):
            draw.line([(x, y - 10), (x, y + 10)], fill="black", width=2)
        draw.text(((margin + width - margin) / 2, y + 14), f"{span_x:.0f}", fill="black",
                  anchor="ma", font=font)
        x = margin - 34
        draw.line([(x, margin), (x, margin + span_y * scale)], fill="black", width=2)
        draw.text((x - 8, margin + span_y * scale / 2), f"{span_y:.0f}", fill="black",
                  anchor="rm", font=font)
    target.parent.mkdir(parents=True, exist_ok=True)
    image.save(target)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description="黑白线稿（正投影）导出")
    parser.add_argument("--model", required=True)
    parser.add_argument("--out-dir", required=True)
    parser.add_argument("--project", default=None)
    parser.add_argument("--views", default="front,top,side")
    parser.add_argument("--formats", default="svg,dxf,png")
    parser.add_argument("--sections", type=int, default=0,
                        help="额外输出 N 个水平剖切轮廓（投影 cut=true，含外轮廓）")
    parser.add_argument("--exploded", type=float, default=None,
                        help="额外输出爆炸状态线稿（值为分离量，单位同模型）")
    parser.add_argument("--title", default=None, help="图题（默认取 storyboard 标题）")
    parser.add_argument("--define", action="append", default=[])
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    root = Path(args.project).resolve() if args.project else Path.cwd()
    settings = load_settings(root)
    openscad = find_openscad()
    if not openscad:
        raise SystemExit("未找到 OpenSCAD，请设置 OPENSCAD_EXECUTABLE")

    model = Path(args.model)
    if not model.is_absolute():
        model = (root / args.model) if (root / args.model).exists() else project_paths(root)["model"] / args.model
    if not model.exists():
        raise SystemExit(f"模型不存在：{model}")
    out_dir = Path(args.out_dir) if Path(args.out_dir).is_absolute() else root / args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    formats = [f.strip() for f in args.formats.split(",") if f.strip()]
    defines = dict(item.split("=", 1) for item in args.define)
    title = args.title
    if title is None:
        storyboard = read_json(paths_storyboard := project_paths(root)["storyboard"], {}) or {}
        title = storyboard.get("title", "")
    else:
        storyboard = {}

    # 需要输出的"视图任务"：常规视图 +（可选）爆炸 +（可选）若干剖切
    jobs: list[dict] = []
    for view in [v.strip() for v in args.views.split(",") if v.strip()]:
        jobs.append({"view": view, "cut": False, "cut_z": None, "explode": None, "suffix": ""})
        if args.exploded:
            jobs.append({"view": view, "cut": False, "cut_z": None,
                         "explode": args.exploded, "suffix": "_exploded"})
        if args.sections:
            bbox = model_extent_for(model)
            if bbox:
                low, high = bbox
                for index in range(1, args.sections + 1):
                    z = low + (high - low) * index / (args.sections + 1)
                    jobs.append({"view": view, "cut": True, "cut_z": z,
                                 "explode": None, "suffix": f"_section{index}"})

    results = []
    with tempfile.TemporaryDirectory(prefix="p3d_lineart_") as tmp:
        temp_dir = Path(tmp)
        for job in jobs:
            view = job["view"]
            rotation = VIEW_ROTATIONS.get(view)
            if rotation is None:
                results.append({"view": view, "ok": False, "error": "未知视角"})
                continue
            tag = f"{view}{job['suffix']}"
            wrapper = wrap_model(model, rotation, temp_dir, defines, cut=job["cut"],
                                 cut_z=job["cut_z"], explode=job["explode"], tag=tag)
            entry = {"view": tag, "ok": False, "files": {}}
            # PNG 只能由 SVG 折线栅格化得到；把 png 交给 OpenSCAD 会导出一张彩色渲染图
            vector_formats = [f for f in formats if f != "png"]
            if "png" in formats and "svg" not in vector_formats:
                vector_formats.append("svg")
            for fmt in vector_formats:
                target = out_dir / f"{model.stem}_{tag}.{fmt}"
                argv = ["-D", f"SET_FN={settings['scad_fn']}",
                        "-D", f"SET_COIL_SEG={settings['scad_coil_seg']}",
                        "-o", str(target), str(wrapper)]
                result = run_cli(openscad, argv, 600)
                if result.returncode != 0 or not target.exists():
                    entry.update(ok=False,
                                 error=(result.stdout + result.stderr).strip()[-800:])
                    break
                entry["files"][fmt] = str(target)
            if entry.get("files", {}).get("svg") and "png" in formats:
                png = Path(entry["files"]["svg"]).with_suffix(".png")
                label = f"{title} {view}图".strip()
                if job["cut"]:
                    label += f"（剖切 z={job['cut_z']:.0f}）"
                elif job["explode"]:
                    label += "（爆炸）"
                if polylines_to_png(svg_polylines(Path(entry["files"]["svg"])), png,
                                    title=label):
                    entry["files"]["png"] = str(png)
            entry["ok"] = entry.get("ok") or bool(entry["files"])
            results.append(entry)

    payload = {"model": str(model), "out_dir": str(out_dir),
               "views": results, "ok": all(r.get("ok") for r in results)}
    if args.json:
        print(json.dumps(payload, ensure_ascii=False, indent=2))
    else:
        for entry in results:
            print(f"{entry['view']:6s} {'OK' if entry.get('ok') else 'FAIL'} "
                  + ", ".join(Path(p).name for p in entry.get("files", {}).values()))
    return 0 if payload["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
