"""Export black-and-white patent-style drawings: orthographic projections.

``projection(cut=false)`` gives the outlines of the model as 2D geometry, which
OpenSCAD can export as SVG and DXF.  DXF opens directly in AutoCAD (add
reference numerals and dimensions there); PNG is produced here by drawing the
SVG polyline data with Pillow, so no extra SVG rasteriser is required.

Usage:
    python lineart.py --model model/device.scad --out-dir figures/黑白附图 \
        [--views front,top,side] [--formats svg,dxf,png] [--json]
"""

from __future__ import annotations

import argparse
import json
import re
import tempfile
from pathlib import Path

from PIL import Image, ImageDraw

from config import find_openscad, load_settings, project_paths, read_json
from openscad_run import run_cli

# view name -> rotation applied before projection() (projects along +Z)
VIEW_ROTATIONS: dict[str, list[int]] = {
    "front": [90, 0, 0],
    "back": [90, 0, 180],
    "side": [90, 0, 90],
    "right": [90, 0, 90],
    "left": [90, 0, -90],
    "top": [0, 0, 0],
    "bottom": [180, 0, 0],
}


def model_extent_for(model: Path) -> tuple[float, float] | None:
    """Z range of the model (used to place section cuts)."""
    try:
        from openscad_run import model_extent

        extent = model_extent(model, {}, load_settings(model.parent.parent))
        if not extent:
            return None
        box = extent.get("center", [0, 0, 0])
        size = extent["size"]
        half = size["z"] / 2
        return (box[2] - half, box[2] + half)
    except Exception:
        return None
PATH_RE = re.compile(r'<path[^>]*d="(?P<d>[^"]+)"', re.DOTALL)
NUMBER_RE = re.compile(r"(-?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?)")
FONT_BOLD = [r"C:\Windows\Fonts\msyhbd.ttc", r"C:\Windows\Fonts\msyh.ttc",
             "/System/Library/Fonts/PingFang.ttc",
             "/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc",
             "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"]


def wrap_model(model: Path, rotation: list[int], temp_dir: Path,
               defines: dict[str, str], *, cut: bool = False,
               cut_z: float | None = None, explode: float | None = None,
               tag: str = "view", projection_mode: str = "both") -> Path:
    """Write a self-contained wrapper that projects *model* after *rotation*.

    The model source is inlined instead of included: OpenSCAD on this platform
    fails to open ``include`` targets whose path contains non-ASCII characters
    (while the same file works fine as the main file).

    ``defines`` are written as assignments *before* the model source — see
    :func:`wrapper_defines` for why they must not go on the command line.

    ``projection_mode``: ``"both"`` keeps the legacy single-wrapper behaviour
    (two projections, ``cut=true`` + ``cut=false``); ``"cut"`` / ``"outline"``
    emit exactly one projection.  The split matters: when a wrapper contains
    both projections, OpenSCAD's SVG export keeps only the *last* one, so the
    section cut silently disappears behind the outline.
    """
    from openscad_run import inline_model, param_preamble

    source = inline_model(model)
    wrapper = temp_dir / f"projected_{tag}.scad"
    define_lines = param_preamble(defines)
    call = "device()"
    if explode is not None:
        call = f"device(explode = {explode})"
    shift = f"translate([0, 0, {-float(cut_z or 0)}]) " if cut else ""
    if cut:
        if projection_mode == "cut":
            body = (f"projection(cut = true) rotate([{rotation[0]}, {rotation[1]}, {rotation[2]}]) "
                    f"{shift}{call};\n")
        elif projection_mode == "outline":
            body = (f"projection(cut = false) rotate([{rotation[0]}, {rotation[1]}, "
                    f"{rotation[2]}]) {call};\n")
        else:
            body = (f"projection(cut = true) rotate([{rotation[0]}, {rotation[1]}, {rotation[2]}]) "
                    f"{shift}{call};\n"
                    f"projection(cut = false) rotate([{rotation[0]}, {rotation[1]}, "
                    f"{rotation[2]}]) {call};\n")
    else:
        body = (f"projection(cut = false) rotate([{rotation[0]}, {rotation[1]}, "
                f"{rotation[2]}]) {call};\n")
    wrapper.write_text(
        f"// generated by lineart.py（模型已内联）\n{define_lines}\n{source}\n"
        f"{body}",
        encoding="utf-8",
    )
    return wrapper


def wrapper_defines(settings: dict, defines: dict[str, str] | None = None) -> dict[str, str]:
    """Parameter values to write into a wrapper, bypassing OpenSCAD's ``-D``.

    ``-D`` values are applied *after* a file's top-level assignments, so the
    usual model idiom — ``BASE_L = is_undef(SET_BASE_L) ? 400 : SET_BASE_L;`` —
    never sees them: ``is_undef()`` is true at that point and the fallback wins
    (verified on OpenSCAD 2026.09; only a direct use inside the geometry, or a
    ``-D`` that shadows a variable the file itself assigns, picks the value up).
    Writing the assignments into the wrapper makes both the fallback expression
    and anything derived from it see the requested values.
    """
    merged: dict[str, str] = {}
    if settings:
        merged["SET_FN"] = str(settings["scad_fn"])
        merged["SET_COIL_SEG"] = str(settings["scad_coil_seg"])
    for key, value in (defines or {}).items():
        merged[key] = str(value)
    return merged


def svg_polylines(svg_path: Path) -> list[list[tuple[float, float]]]:
    text = svg_path.read_text(encoding="utf-8", errors="replace")
    polylines: list[list[tuple[float, float]]] = []
    for match in PATH_RE.finditer(text):
        current: list[tuple[float, float]] = []
        for chunk in re.split(r"(?=[MLZ])", match.group("d")):
            chunk = chunk.strip()
            if not chunk:
                continue
            if chunk[0] in "MZ":
                if len(current) > 1:
                    polylines.append(current)
                current = []
                numbers = [float(v) for v in NUMBER_RE.findall(chunk[1:])]
                if len(numbers) >= 2:
                    current = [(numbers[0], numbers[1])]
            elif chunk[0] == "L":
                numbers = [float(v) for v in NUMBER_RE.findall(chunk[1:])]
                for i in range(0, len(numbers) - 1, 2):
                    current.append((numbers[i], numbers[i + 1]))
        if len(current) > 1:
            polylines.append(current)
    return polylines


def polylines_to_png(polylines: list[list[tuple[float, float]]], target: Path,
                     width: int = 1600, margin: int = 110, line_width: int = 3,
                     title: str = "", annotate_size: bool = True) -> bool:
    points = [p for line in polylines for p in line]
    if not points:
        return False
    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    span_x, span_y = max(xs) - min(xs), max(ys) - min(ys)
    scale = (width - 2 * margin) / max(span_x, 1e-9)
    height = int(span_y * scale) + 2 * margin
    image = Image.new("RGB", (width, max(height, 200) + 60), "white")
    draw = ImageDraw.Draw(image)
    for line in polylines:
        pixels = [((x - min(xs)) * scale + margin, (max(ys) - y) * scale + margin) for x, y in line]
        draw.line(pixels, fill="black", width=line_width, joint="curve")
    if title:
        from PIL import ImageFont

        font = None
        for path in FONT_BOLD:
            if Path(path).exists():
                font = ImageFont.truetype(path, 34)
                break
        draw.text((width / 2, 18), title, fill="black", anchor="ma",
                  font=font or ImageFont.load_default())
    if annotate_size and span_x:
        # 尺寸线：横向总宽 / 纵向总高（单位与被投影模型一致，通常为 mm）
        from PIL import ImageFont

        font = None
        for path in FONT_BOLD:
            if Path(path).exists():
                font = ImageFont.truetype(path, 26)
                break
        font = font or ImageFont.load_default()
        y = max(height, 200) - margin + 26
        draw.line([(margin, y), (width - margin, y)], fill="black", width=2)
        for x in (margin, width - margin):
            draw.line([(x, y - 10), (x, y + 10)], fill="black", width=2)
        draw.text(((margin + width - margin) / 2, y + 14), f"{span_x:.0f}", fill="black",
                  anchor="ma", font=font)
        x = margin - 34
        draw.line([(x, margin), (x, margin + span_y * scale)], fill="black", width=2)
        draw.text((x - 8, margin + span_y * scale / 2), f"{span_y:.0f}", fill="black",
                  anchor="rm", font=font)
    target.parent.mkdir(parents=True, exist_ok=True)
    image.save(target)
    return True


def build_jobs(views: list[str], exploded: float | None, sections: int,
               top_section: int, extent_fn) -> list[dict]:
    """Compose the projection jobs: regular views + explosion + section cuts.

    ``extent_fn()`` returns the model's Z range ``(low, high)`` or ``None``
    (used to place section cuts; called lazily, once for the top/bottom auto-cut
    and again for the explicit ``--sections``).  Separated from ``main`` so the
    view/task selection logic is unit-testable without OpenSCAD.
    """
    jobs: list[dict] = []
    top_bbox: tuple[float, float] | None = None
    for view in views:
        jobs.append({"view": view, "cut": False, "cut_z": None, "explode": None, "suffix": ""})
        if exploded:
            jobs.append({"view": view, "cut": False, "cut_z": None,
                         "explode": exploded, "suffix": "_exploded"})
        # top/bottom 的俯视投影会被顶/底板盖成空框：默认补水平剖切看内部
        if view in ("top", "bottom") and top_section:
            if top_bbox is None:
                top_bbox = extent_fn()
            if top_bbox:
                low, high = top_bbox
                for index in range(1, top_section + 1):
                    z = low + (high - low) * (0.4 + 0.4 * index / (top_section + 1))
                    jobs.append({"view": view, "cut": True, "cut_z": z,
                                 "explode": None, "suffix": f"_section{index}"})
        if sections:
            bbox = extent_fn()
            if bbox:
                low, high = bbox
                for index in range(1, sections + 1):
                    z = low + (high - low) * index / (sections + 1)
                    jobs.append({"view": view, "cut": True, "cut_z": z,
                                 "explode": None, "suffix": f"_section{index}"})
    return jobs


def merge_svg(target: Path, sources: list[Path]) -> None:
    """Merge several same-viewBox SVG files (path elements only) into one file.

    Section cuts are rendered as two wrappers (cut=true + cut=false) because
    OpenSCAD's SVG export keeps only the *last* top-level projection; merging
    here restores the single-file deliverable with both the section and the
    outline.
    """
    header = '<svg xmlns="http://www.w3.org/2000/svg">'
    body: list[str] = []
    for index, source in enumerate(sources):
        text = source.read_text(encoding="utf-8", errors="replace")
        if index == 0:
            match = re.search(r"<svg[^>]*>", text)
            if match:
                header = match.group(0)
        body.extend(re.findall(r"<path\b[^>]*/>", text, re.DOTALL))
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        '<?xml version="1.0" standalone="no"?>\n' + header + "\n"
        + "\n".join(body) + "\n</svg>\n", encoding="utf-8")


def split_dxf(text: str) -> tuple[list[str], list[str], list[str]]:
    """Split an OpenSCAD ASCII DXF into (head, ENTITIES records, tail).

    OpenSCAD writes HEADER/TABLES/BLOCKS/ENTITIES sections; the split wrappers
    of one section job differ only inside ENTITIES, so head + both record
    blocks + tail is a valid single DXF.
    """
    lines = text.splitlines()
    for index in range(len(lines) - 3):
        if (lines[index].strip() == "0" and lines[index + 1].strip() == "SECTION"
                and lines[index + 3].strip() == "ENTITIES"):
            body = index + 4
            for end in range(body, len(lines) - 1):
                if lines[end].strip() == "0" and lines[end + 1].strip() == "ENDSEC":
                    return lines[:body], lines[body:end], lines[end:]
            return lines[:body], lines[body:], []
    return lines, [], []


def merge_dxf(target: Path, sources: list[Path]) -> None:
    """Merge same-model DXF exports (section cut + outline) into one file.

    ``--formats dxf`` promises one DXF per view, but a section job is exported
    as two wrappers (see ``merge_svg``) and would otherwise ship as a
    ``*_cut.dxf`` + ``*_out.dxf`` pair.  The two files come from the same model
    and header, so splicing their ENTITIES records restores the single-file
    deliverable that goes straight into AutoCAD.
    """
    head, body, tail = split_dxf(sources[0].read_text(encoding="ascii", errors="replace"))
    for source in sources[1:]:
        body.extend(split_dxf(source.read_text(encoding="ascii", errors="replace"))[1])
    target.parent.mkdir(parents=True, exist_ok=True)
    with target.open("w", encoding="ascii", errors="replace", newline="\n") as handle:
        handle.write("\n".join(head + body + tail) + "\n")


def main() -> int:
    from config import enable_utf8_stdout
    enable_utf8_stdout()
    parser = argparse.ArgumentParser(description="黑白线稿（正投影）导出")
    parser.add_argument("--model", required=True)
    parser.add_argument("--out-dir", required=True)
    parser.add_argument("--project", default=None)
    parser.add_argument("--views", default="front,top,side")
    parser.add_argument("--formats", default="svg,dxf,png")
    parser.add_argument("--sections", type=int, default=0,
                        help="额外输出 N 个水平剖切轮廓（投影 cut=true，含外轮廓）")
    parser.add_argument("--top-section", type=int, default=1,
                        help="top/bottom 视图自动追加 N 个水平剖切（默认 1；俯视投影时顶板/底板会盖住"
                             "内部构件，只剩外框剪影，剖切才能看到内部轮廓）")
    parser.add_argument("--exploded", type=float, default=None,
                        help="额外输出爆炸状态线稿（值为分离量，单位同模型）")
    parser.add_argument("--title", default=None, help="图题（默认取 storyboard 标题）")
    parser.add_argument("--define", action="append", default=[])
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    root = Path(args.project).resolve() if args.project else Path.cwd()
    settings = load_settings(root)
    openscad = find_openscad()
    if not openscad:
        raise SystemExit("未找到 OpenSCAD，请设置 OPENSCAD_EXECUTABLE")

    model = Path(args.model)
    if not model.is_absolute():
        model = (root / args.model) if (root / args.model).exists() else project_paths(root)["model"] / args.model
    if not model.exists():
        raise SystemExit(f"模型不存在：{model}")
    out_dir = Path(args.out_dir) if Path(args.out_dir).is_absolute() else root / args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    formats = [f.strip() for f in args.formats.split(",") if f.strip()]
    defines = dict(item.split("=", 1) for item in args.define)
    title = args.title
    if title is None:
        storyboard = read_json(paths_storyboard := project_paths(root)["storyboard"], {}) or {}
        title = storyboard.get("title", "")
    else:
        storyboard = {}

    # 需要输出的"视图任务"：常规视图 +（可选）爆炸 +（可选）若干剖切
    jobs = build_jobs([v.strip() for v in args.views.split(",") if v.strip()],
                      args.exploded, args.sections, args.top_section,
                      lambda: model_extent_for(model))

    results = []
    with tempfile.TemporaryDirectory(prefix="p3d_lineart_") as tmp:
        temp_dir = Path(tmp)
        for job in jobs:
            view = job["view"]
            rotation = VIEW_ROTATIONS.get(view)
            if rotation is None:
                results.append({"view": view, "ok": False, "error": "未知视角"})
                continue
            tag = f"{view}{job['suffix']}"
            entry: dict = {"view": tag, "ok": False, "files": {}}
            # PNG 只能由 SVG 折线栅格化得到；把 png 交给 OpenSCAD 会导出一张彩色渲染图
            vector_formats = [f for f in formats if f != "png"]
            if "png" in formats and "svg" not in vector_formats:
                vector_formats.append("svg")
            # 剖切任务拆成断面(cut) + 外轮廓(outline) 两个 wrapper：OpenSCAD 的 SVG
            # 导出在同一文件里放两个 projection 时只保留最后一个，断面会被外框吞掉
            subtasks = ([("_cut", {"cut": True, "cut_z": job["cut_z"]}),
                         ("_out", {"cut": False, "cut_z": None})]
                        if job["cut"] else
                        [("", {"cut": False, "cut_z": None})])
            svg_sources: list[Path] = []
            dxf_sources: list[Path] = []
            error = None
            for sub_suffix, params in subtasks:
                wrapper = wrap_model(model, rotation, temp_dir,
                                     wrapper_defines(settings, defines),
                                     explode=job["explode"], tag=f"{tag}{sub_suffix}",
                                     projection_mode="cut" if params["cut"] else "outline",
                                     **params)
                for fmt in vector_formats:
                    target = out_dir / f"{model.stem}_{tag}{sub_suffix}.{fmt}"
                    argv = ["-o", str(target), str(wrapper)]
                    result = run_cli(openscad, argv, 600)
                    if result.returncode != 0 or not target.exists():
                        error = (result.stdout + result.stderr).strip()[-800:]
                        break
                    if fmt == "svg":
                        svg_sources.append(target)
                    elif fmt == "dxf":
                        dxf_sources.append(target)
                        entry["files"][f"{fmt}_{sub_suffix or 'view'}"] = str(target)
                    else:
                        entry["files"][f"{fmt}_{sub_suffix or 'view'}"] = str(target)
                if error:
                    break
            if error:
                entry.update(ok=False, error=error)
                results.append(entry)
                continue
            # 合并 SVG / PNG：断面 + 外轮廓合成一份交付
            if svg_sources:
                merged = out_dir / f"{model.stem}_{tag}.svg"
                merge_svg(merged, svg_sources)
                entry["files"]["svg"] = str(merged)
            # DXF 同样只交付一份：单 wrapper 时就是它本身，剖切时把两个 wrapper
            # 的 ENTITIES 段拼起来（否则交付目录里只剩 *_cut.dxf + *_out.dxf）
            if len(dxf_sources) == 1:
                entry["files"]["dxf"] = str(dxf_sources[0])
            elif len(dxf_sources) > 1:
                merged_dxf = out_dir / f"{model.stem}_{tag}.dxf"
                merge_dxf(merged_dxf, dxf_sources)
                entry["files"]["dxf"] = str(merged_dxf)
            if svg_sources and "png" in formats:
                png = out_dir / f"{model.stem}_{tag}.png"
                label = f"{title} {view}图".strip()
                if job["cut"]:
                    label += f"（剖切 z={job['cut_z']:.0f}）"
                elif job["explode"]:
                    label += "（爆炸）"
                polylines = [line for src in svg_sources for line in svg_polylines(src)]
                if polylines_to_png(polylines, png, title=label):
                    entry["files"]["png"] = str(png)
            entry["ok"] = bool(entry["files"])
            results.append(entry)

    payload = {"model": str(model), "out_dir": str(out_dir),
               "views": results, "ok": all(r.get("ok") for r in results)}
    if args.json:
        print(json.dumps(payload, ensure_ascii=False, indent=2))
    else:
        for entry in results:
            print(f"{entry['view']:6s} {'OK' if entry.get('ok') else 'FAIL'} "
                  + ", ".join(Path(p).name for p in entry.get("files", {}).values()))
    return 0 if payload["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
